const styles = {
  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#1a0a00",
    color: "#f5c842",
    fontFamily: "'Quicksand', sans-serif",
    width: "100%",
    overflowX: "hidden",
  },

  cabecalho: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.8rem 1.5rem",
    borderBottom: "2px solid #c45c00",
    backgroundColor: "#2a1000",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  cabecalhoLogo: {
    fontSize: "1.4rem",
    fontWeight: "700",
    letterSpacing: "0.2em",
    color: "#ffb347",
    textTransform: "uppercase",
  },
  cabecalhoNav: {
    display: "flex",
    gap: "0.5rem",
  },
  cabecalhoBtn: {
    backgroundColor: "#3d1800",
    border: "1px solid #c45c00",
    color: "#ffb347",
    padding: "0.45rem 1.2rem",
    fontSize: "1rem",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    cursor: "pointer",
    transition: "all 0.18s ease",
    fontFamily: "'Quicksand', sans-serif",
    borderRadius: "6px",
  },
  cabecalhoBtnAtivo: {
    backgroundColor: "#c45c00",
    borderColor: "#c45c00",
    color: "#fff8f0",
  },

  rodape: {
    marginTop: "auto",
    padding: "0.8rem 1.5rem",
    borderTop: "2px solid #c45c00",
    backgroundColor: "#2a1000",
    textAlign: "center",
  },
  rodapeLink: {
    color: "#ffb347",
    textDecoration: "none",
    fontSize: "0.85rem",
    letterSpacing: "0.12em",
    display: "block",
    marginBottom: "0.4rem",
    fontFamily: "'Quicksand', sans-serif",
  },
  rodapeTexto: {
    color: "#a0622a",
    fontSize: "0.78rem",
    letterSpacing: "0.08em",
    fontFamily: "'Quicksand', sans-serif",
  },

  main: {
    flex: 1,
    padding: "1.5rem 1.5rem 5rem 1.5rem",
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    overflowX: "hidden",
    backgroundColor: "#3d1a00",
  },
  menu: {
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: "2.5rem",
    paddingBottom: "2rem",
    borderBottom: "2px solid #c45c00",
    justifyContent: "center",
  },

  botao: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.6rem",
    backgroundColor: "#2a1000",
    border: "1px solid #c45c00",
    padding: "1rem 1.2rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: "'Quicksand', sans-serif",
    minWidth: "90px",
    flex: "1 1 80px",
    maxWidth: "130px",
    borderRadius: "12px",
    outline: "none",
    WebkitAppearance: "none",
    WebkitTapHighlightColor: "transparent",
  },
  botaoAtivo: {
    borderColor: "#ffb347",
    backgroundColor: "#4d2200",
    boxShadow: "0 0 14px #c45c0055",
  },
  botaoFoto: {
    width: "64px",
    height: "64px",
    objectFit: "cover",
    border: "2px solid #c45c00",
    display: "block",
    margin: "0 auto",
    transition: "transform 0.2s ease",
    borderRadius: "12px",
  },
  botaoFotoPlaceholder: {
    width: "64px",
    height: "64px",
    backgroundColor: "#4d2200",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.4rem",
    border: "2px solid #c45c00",
    margin: "0 auto",
    borderRadius: "12px",
  },
  botaoNome: {
    fontSize: "0.9rem",
    color: "#ffb347",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    textAlign: "center",
    fontFamily: "'Quicksand', sans-serif",
  },
  botaoNomeAtivo: {
    color: "#ffe0a0",
  },

  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 480px), 1fr))",
    gap: "1.2rem",
  },

  card: {
    border: "1px solid #c45c0055",
    backgroundColor: "#2a1200",
    padding: "1.2rem 1.5rem",
    position: "relative",
    borderRadius: "12px",
    boxShadow: "0 2px 12px #00000044",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },

  cardTag: {
    display: "inline-block",
    fontSize: "0.75rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    padding: "0.25rem 0.8rem",
    marginBottom: "0.8rem",
    borderRadius: "999px",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: "700",
  },
  cardTagFacil: { backgroundColor: "#3d2000", color: "#ffb347", border: "1px solid #c45c00" },
  cardTagDificil: { backgroundColor: "#3d0a00", color: "#ff6b35", border: "1px solid #ff4500" },
  cardTagAprendizado: { backgroundColor: "#3d2800", color: "#ffd580", border: "1px solid #e8a000" },
  cardTagSemAprendizado: { backgroundColor: "#1a1000", color: "#a07040", border: "1px solid #6b4a20" },

  cardTitulo: {
    fontSize: "1rem",
    color: "#ffe0a0",
    letterSpacing: "0.1em",
    marginBottom: "0",
    textTransform: "uppercase",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: "700",
  },

  cardCodigo: {
    backgroundColor: "#1a0a00",
    border: "1px solid #c45c0044",
    padding: "1rem 1.2rem",
    overflowX: "auto",
    fontSize: "0.78rem",
    lineHeight: "1.8",
    color: "#ffd580",
    fontFamily: "monospace",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    borderRadius: "8px",
    margin: "0",
    maxWidth: "100%",
  },

  cardComentario: {
    marginTop: "1rem",
    fontSize: "0.82rem",
    color: "#c47a3a",
    fontStyle: "italic",
    lineHeight: "1.6",
    borderTop: "1px solid #c45c0044",
    paddingTop: "0.8rem",
    fontFamily: "'Quicksand', sans-serif",
  },

  cardSeta: {
    fontSize: "0.8rem",
    color: "#ffb347",
    flexShrink: 0,
    letterSpacing: "0.05em",
  },

  conteudo: {
    maxWidth: "750px",
    margin: "0 auto",
    textAlign: "center",
  },
  conteudoTitulo: {
    fontSize: "1rem",
    letterSpacing: "0.25em",
    color: "#ffb347",
    textTransform: "uppercase",
    marginBottom: "2.5rem",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: "700",
    textAlign: "center",
  },
  conteudoLista: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  conteudoItem: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "0.5rem",
    padding: "1.2rem 1.5rem",
    borderRadius: "12px",
    backgroundColor: "#2a1200",
    boxShadow: "0 2px 12px #00000044",
    textAlign: "center",
    border: "1px solid #c45c0055",
  },
  conteudoNome: {
    fontSize: "1rem",
    color: "#ffe0a0",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: "700",
  },
  conteudoDescricao: {
    fontSize: "0.85rem",
    color: "#c47a3a",
    lineHeight: "1.7",
    fontFamily: "'Quicksand', sans-serif",
  },
};

export default styles;